<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>NosCore</Authors>
    <Copyright>2022</Copyright>
    <Nullable>enable</Nullable>
    <PackageProjectUrl>https://github.com/NosCoreIO/NosCore.Dao</PackageProjectUrl>
    <RepositoryUrl>https://github.com/NosCoreIO/NosCore.Dao.git</RepositoryUrl>
    <PackageIconUrl></PackageIconUrl>
    <PackageTags>nostale, noscore, nostale private server source, nostale emulator</PackageTags>
    <Version>6.0.0</Version>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <Description>NosCore's Shared Components</Description>
    <PackageLicenseExpression></PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <Company>NosCore</Company>
    <PackageIcon>icon.png</PackageIcon>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>CS1591</WarningsNotAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\build\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.7" />
    <PackageReference Include="NetEscapades.Configuration.Yaml" Version="3.1.0" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.6" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\icon.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
